### PR TITLE
Fix static

### PR DESCRIPTION
**Pull request by kelepirci**

### CODE REVIEW

**Comment by sametbalta** [comment]
I think there is a wrong GIT usage here. Merging master branch into feature branches is not preferred way. Unless we don't have huge conflicts, rebase is better answer. 

https://stackoverflow.com/questions/16955980/git-merge-master-into-feature-branch

**Comment by kelepirci** [comment]
Hi Samat,

Thank you for pointing out about this. But this way of working was intentional from my side.

Here is my commit order:

1-) I fork the original repository (palamar:master) to my personal account.
2-) I create a new branch for every feature, bug fix or anything that I want to create as a new branch in my personal account.
3-) After I have satisfied with with my work, I open a new pull request with specific branch.
4-) If pull request is reviewed and confirmed by at leas one confirmed contributor, the pull request will be merged with master.
5-) In mean time my privately forked repository does not have the updated master branch. So I also create a pull request from my private repo to get updates.

I have learned this way of working from OpenStack and according to google searches and bunch of how to use Github videos, this seems to a good way contribute.

P.S. I should create a new contributor document and add these to there.

**Comment by kelepirci** [comment]
Hi Again,

I think you are talking about "Merge pull request #9 from palamario/master". This is the commit from my private palamar repo. This is not suppose to show up here.

Let me check what is wrong.

**Comment by kelepirci** [comment]
Because of Samet's review. I will close this pull request and fix the branching problem and will create another pull request.

**Pull request closed without merging**
